### ISSUE TITLE
InvalidSchema: No connection adapters were found for

### ISSUE THREAD

**Issue by BillyBSig** [dfreelon/pyktok#32]
Hi, I get this error, "InvalidSchema: No connection adapters were found for"
Do you have solution for this issue?

![error_pyktok](https://github.com/dfreelon/pyktok/assets/104679486/74506ee4-b88e-4973-8a97-619f689f9f04)

**Comment by dfreelon** [comment]
Removing the curly braces from your URL should fix the problem.

**Comment by BillyBSig** [comment]
Hi, i remove the curly braces, but still get another issue,

import pyktok as pyk
pyk.specify_browser("firefox")
pyk.save_tiktok("https://www.tiktok.com/@vantoan___/video/7294298719665622305?is_from_webapp=1&sender_device=pc",
                True,
                    'video_data.csv',
            browser_name = "firefox")


![NoneType](https://github.com/dfreelon/pyktok/assets/104679486/91d4adfc-8103-4090-8b11-6d75b7b1a8ce)
